Lights: 
    hostname: "192.168.0.59"
    token: "3cae5b382976779f2f30cce81ea78faf"
    targets: 
        - Licht
        - Lichter
    devices: ["WZ Links", "WZ Rechts", "WZ Back", "WZ Back Links", "Flur", "SZ I", "SZ O 1", "AZ Vorne", "AZ Hinten"]
    services:
        Alle Aus: []
        Alle An: ["WZ Links", "WZ Rechts", "WZ Back", "WZ Back Links", "Flur", "SZ I", "SZ O 1", "AZ Vorne", "AZ Hinten"]
        Schlafzimmer: ["SZ I", "SZ O 1"]
        Arbeitszimmer: [ "AZ Vorne", "AZ Hinten"]
        Wohnzimmer: ["WZ Links", "WZ Rechts", "WZ Back", "WZ Back Links"]
        Flur: [ "Flur"]
    commands: 
        - turnon
        - turnoff
        - increase
        - decrease
Wol:
    devices: ["Nas"]
    services:
        Nas: Nas
XBMC: 
    ip: ['192.168.0.39', '192.168.0.21']
    actions:
        Random FamilyGuy: "Family Guy"
Harmony Hub: 
    ip: '192.168.0.32'
    devices: ["Fernseher"]
    targets: 
        - Fernsehen
    services:
        Fernsehen: 
            activity: 'Fernsehen'
            action: on
        Fernseher ausschalten:
            activity: 'Fernsehen'
            action: off
    commands: 
        - turnon
        - turnoff
        - switchto
Yamaha: 
    devices: ["Receiver"]
    targets: 
        - Receiver
        - Musik
        - Lautstärke
    ip: '192.168.0.25'
    commands: 
        - play
        - increase
        - decrease
Speech:
    -
      match: ["Alle Lichter An"]
      services: 
        - Alle An
    -
      match: ["Alle Lichter Aus"]
      services: 
        - Alle Aus
    -
      match: ["Licht an"]
      services: 
        - Wohnzimmer
    -
      match: ["Gute Nacht"]
      services: 
        - Alle Aus
        - Fernsehen Stop
    -
      match: ["abgehts"]
      services: 
        - Wohnzimmer
    -
      match: ["テレビ お願いします"]
      services: 
        - Fernsehen
    -
      match: ["テレビ 終わって お願いします", "テレビ 終わってください", "テレビ スイッチを切るお願いします"]
      services: 
        - Fernseher ausschalten
Rooms: 
    - Wohnzimmer
    - Schlafzimmer
    - Arbeitszimmer
    - Flur
Devices: 
    Receiver:
        location: Wohnzimmer 
    Fernseher:
        location: Wohnzimmer 
    XBMC Schlafzimmer:
        location: Schlafzimmer
    Nas:
        location: Arbeitszimmer
        mac: 'bc:5f:f4:cd:e0:3b'
    Fernseher:
        location: Wohnzimmer 
    WZ Links:
        location: Wohnzimmer 
    WZ Rechts:
        location: Wohnzimmer 
    WZ Back:
        location: Wohnzimmer 
    WZ Back Links:
        location: Wohnzimmer 
    Flur:
        location: Flur 
    SZ I:
        location: Schlafzimmer 
    SZ O 1:
        location: Schlafzimmer 
    AZ Vorne:
        location: Arbeitszimmer 
    AZ Hinten:
        location: Arbeitszimmer 
Languages: # ISO 639-1
    - de
    - en
    - ja
SynonymHints:
    play: ["abspielen", "spielen"]
    switchto: ["umschalten"]
    turnon: ["an", "einschalten", "anschalten", "aktivieren", "anknipsen", "anmachen"]
    turnoff: ["aus" , "abschalten", "ausmachen", "ausschalten", "turn off", "ausknipsen", "eliminieren",
                "liquidieren", "neutralisieren", "terminieren", "スイッチを切る"]
    increase: ["erhöhen", "anheben", "lauter", "hell", "heller"]
    decrease: ["leiser", "absenken", "reduzieren", "dimmen", "dimme"]
    fernsehen: ["fernseher", "fernsehen", "tv"]
    licht: ["lichter", "lights"]
    receiver: ["Verstärker"]